[tool.poetry]
name = "task10-3"
version = "0.1.0"
description = ""
authors = ["Mikhail Kuznetsov <k9140707193@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
